disabled_rules:
  - cyclomatic_complexity
  - todo
  - trailing_whitespace
  - vertical_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
line_length:
  warning: 140
  error: 1000
identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
