# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OsirisIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
  pod 'SwiftLint'

  # Pods for OsirisIOS

  target 'OsirisIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OsirisIOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
